services:
  db:
    image: postgres:15-alpine
    container_name: currency_exchange_db
    environment:
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password
      POSTGRES_DB: exchange_db
    volumes:
      - exchange_db_data:/var/lib/postgresql/data
      - ./src/database/init_db.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app_user"]
      interval: 5s
      timeout: 5s
      retries: 5
  app:
    build: .
    container_name: currency_exchange_app
    environment:
      DATABASE_URL: postgresql://app_user:app_password@db:5432/exchange_db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./src:/app/src
  test:
    build: .
    container_name: currency_exchange_tests
    environment:
      DATABASE_URL: postgresql://app_user:app_password@db:5432/exchange_db
      PYTHONPATH: /app  # <- Esto es clave
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    working_dir: /app
    command: pytest



volumes:
  exchange_db_data: